codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%    # Minimum required code coverage
        threshold: 2%   # Maximum allowed coverage decrease
    patch:
      default:
        target: 80%    # Required coverage for new/modified lines
        threshold: 0%   # No coverage decrease allowed in changed files
    
    # Custom rules for different parts of the code
    changes: no  # Don't fail the build if coverage of changes drops

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Ignore test files and examples
ignore:
  - "tests/**/*"
  - "examples/**/*"
